[CMS-240] Create a Terminus plugin command to turn on the build step
pantheon-systems/terminus-conversion-tools-plugin pull request #13
Opened 2021-12-23 11:49 UTC by jabxjab

2021-12-23 16:38 UTC, uberhacker commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $this->getGit()->commit(
How about setting `$composer = $this->getComposer()` and `$git = $this->getGit()`?

2021-12-23 16:41 UTC, uberhacker commented on src/Commands/EnableIntegratedComposerCommand.php
> +        $this->log()->notice('Done!');
How about `$git = $this->getGit()` and `$log = $this->log()`?

2021-12-23 16:42 UTC, uberhacker commented on src/Commands/EnableIntegratedComposerCommand.php
> +        if (0 === count($paths)) {
`if (count($paths)) {` should be good enough.

2021-12-23 17:01 UTC, greg-1-anderson commented on src/Commands/EnableIntegratedComposerCommand.php
> +        if (0 === count($paths)) {
`!count()`

2021-12-23 17:02 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $this->getGit()->commit(
I don't think we need or want extra local variables in instances like this.

2021-12-23 17:13 UTC, uberhacker commented on src/Commands/EnableIntegratedComposerCommand.php
> +        if (0 === count($paths)) {
Right!

2021-12-23 20:02 UTC, uberhacker commented on src/Commands/EnableIntegratedComposerCommand.php
> +        if (0 === count($paths)) {
Could also use `if (empty($paths)) {` if negation logic is not preferred.

2021-12-23 20:09 UTC, uberhacker commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $this->getGit()->commit(
I was just thinking `$this->getGit()` is referenced 10+ times so `$git` would avoid typing out the extra characters.  Also, if `$this->getGit()` is changed to something else, setting `$git = <something else>` in one place would be easier.

2021-12-24 06:43 UTC, jabxjab commented on src/Commands/EnableIntegratedComposerCommand.php
> +        $this->log()->notice('Done!');
I would avoid introducing extra vars for such cases

2021-12-24 06:44 UTC, jabxjab commented on src/Commands/EnableIntegratedComposerCommand.php
> +        if (0 === count($paths)) {
updated

2021-12-24 06:56 UTC, jabxjab commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $this->getGit()->commit(
Agree with @greg-1-anderson. To my opinion, this would introduce an extra complexity

2021-12-24 14:41 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $this->getGit()->commit(
There are places where e.g. code will say `$filesystem = new Filesystem()` and then use the instance variable, so I won't say it's wrong; I just don't think that we should be prescriptive about this sort of thing.

2021-12-24 14:57 UTC, greg-1-anderson commented on src/Commands/EnableIntegratedComposerCommand.php
> +
Could we also add a guard here to catch folks who are using this command incorrectly, e.g. if someone runs on a drops-8 site, it would be useful to tell them to use the convert to composer command instead.

I'm not sure how practical this request is, though. If the site is a Drupal site, we could require that drupal/core or drupal/core-recommended is a dependency of the project. I guess for WordPress sites we could require pantheon-systems/wordpress-composer. This is not necessarily going to always hold, e.g. for Bedrock sites. Maybe we should have a short list of Composer-managed cores, and require that the site have at least one? That is, if core is not upgradable via Composer, then exit with an error.

What do you think?

2021-12-24 14:59 UTC, greg-1-anderson commented on src/Commands/EnableIntegratedComposerCommand.php
> +        )) {
I'm not sure that this should be a feature. We don't know if the build step worked, or if the site is in a usable state. It seems that pushing to master here would always be premature. Maybe just advise about the merge-to-dev command, and leave it at that?

2021-12-24 15:04 UTC, greg-1-anderson commented on src/Commands/Traits/ComposerAwareTrait.php
> +trait ComposerAwareTrait
I am ambivalent about this. If we do it like this, then Terminus is going to have a copy of Composer in its dependencies directory, and the Composer version used by these commands will be different than the Composer in the user's PATH. It also seems like we are taking on additional maintenance burden, e.g. if the Composer API changed. Perhaps the odds of that are low, but maybe we should just `exec` Composer, as we usually do?

What do you think?

2021-12-24 15:09 UTC, greg-1-anderson commented on src/Commands/Traits/Drupal8ProjectsAwareTrait.php
> +trait Drupal8ProjectsAwareTrait
Why make a trait for this? Seems like clients can just user `new Drupal8Projects($path);`? There's no DI happening here.

2021-12-24 15:12 UTC, greg-1-anderson commented on src/Commands/Traits/MultidevBranchAwareTrait.php
> +trait MultidevBranchAwareTrait
I'm also wondering why this is a trait. There's only one client class, and the only service provided is a length check, and it's implemented as a side effect. I think that Terminus may have more comprehensive methods for validating multidev names already (e.g. they cannot begin or end with a `-`).

2021-12-24 15:16 UTC, greg-1-anderson requested changes
Looks really good. Not sure my suggestions are even required, but let's discuss.

2022-01-10 07:26 UTC, jabxjab commented on src/Commands/Traits/ComposerAwareTrait.php
> +trait ComposerAwareTrait
@greg-1-anderson I think there is some misunderstanding here. This trait is just a wrapper on top of the existing `Composer` class that actually uses `Process` to call a command. I assume that `setComposer(string $path)` confused you like setting the Composer binary path. The `$path` is a site's working directory in this case. Fixed by renaming args into `$projectPath`

2022-01-10 07:37 UTC, jabxjab commented on src/Commands/Traits/MultidevBranchAwareTrait.php
> +trait MultidevBranchAwareTrait
@greg-1-anderson This trait is used in 4 (out of 7) commands, that is why I made it (branch validation) as a trait. Before introducing validation logic, I've searched across Terminus code and did not find a method for validating a multidev name.

2022-01-10 07:38 UTC, jabxjab commented on src/Commands/Traits/Drupal8ProjectsAwareTrait.php
> +trait Drupal8ProjectsAwareTrait
@greg-1-anderson Agree, removed the trait

2022-01-10 07:39 UTC, jabxjab commented on src/Commands/EnableIntegratedComposerCommand.php
> +        )) {
@greg-1-anderson Updated (removed an option for immediate push to master)

2022-01-10 08:16 UTC, jabxjab commented on src/Commands/EnableIntegratedComposerCommand.php
> +
@greg-1-anderson Agree, this change would be helpful. Implemented an improved validation.

2022-01-10 14:26 UTC, uberhacker commented on src/Commands/AdviseCommand.php
>          );
I like this:
```
    public function advise(string $site_id): void
    {
        $site = $this->getSite($site_id);
        $upstreamId = $site->getUpstream()->get('machine_name');
        $this->writeln(
            sprintf(
                'The site %s uses "%s" (%s) upstream.',
                $site->getName(),
                $site->getUpstream()->get('label'),
                $upstreamId
            )
        );
```

2022-01-10 21:09 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
>          );
While in general I prefer the style recommended by this comment, in the current implementation it's necessary to call `setSite`, as this does the DI for the traits used by this class. My usual preference is for complex traits to be implemented instead as classes, Terminus core follows this same pattern of traits, so it's okay to continue in the same vein here.

2022-01-10 21:12 UTC, greg-1-anderson commented on src/Commands/Traits/ConversionCommandsTrait.php
> +    private function setSite(string $siteId): void
I would prefer to see `protected` used for methods that are intended to be called by classes that use the trait, and reserve `private` for methods that are only intended to be called by other methods in the trait itself.

2022-01-10 21:14 UTC, greg-1-anderson approved these changes
LGTM. I have a preference for some of the private trait methods to be public, but that's optional.

2022-01-10 21:44 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
>          );
See the docblock at the top of the method: `@command conversion:advise`. This is the entry point to a cli command, not a utility method. Command entrypoints must call setSite, because setSite is part of a trait that is not part of the DI system.

2022-01-11 08:39 UTC, jabxjab commented on src/Commands/Traits/ConversionCommandsTrait.php
> +    private function setSite(string $siteId): void
@greg-1-anderson Updated

2022-01-11 10:57 UTC, merged