[CMS-552] Improve advice texts.
pantheon-systems/terminus-conversion-tools-plugin pull request #15
Opened 2022-01-27 00:12 UTC by kporras07

2022-01-28 07:23 UTC, jabxjab requested changes

2022-01-28 07:23 UTC, jabxjab commented on src/Commands/AdviseCommand.php
> +    private function getUpstreamExtraAdvice(string $upstream_id): string
@kporras07 camelcase var names are used across the project. Could you please rename the argument into `$upsteamId`?

2022-01-28 07:23 UTC, jabxjab commented on src/Utils/Git.php
> -        $this->execute(['remote', 'add', $name, $remote]);
@kporras07 What was the reason for adding this?

2022-01-28 12:50 UTC, kporras07 commented on src/Utils/Git.php
> -        $this->execute(['remote', 'add', $name, $remote]);
If you run advise twice, the second time it will fail because it reuses the repo and it already has the remote. I'm adding a check here to ensure that doesn't happen

2022-01-31 07:02 UTC, jabxjab approved these changes

2022-01-31 23:17 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +            return 'This site was created by the process described by the Terminus Build Tools guide (https://pantheon.io/docs/guides/build-tools/).';
There are multiple reasons that a site might be set to the empty upstream; one example is if the site was using the "No CI workflow" . I can't link you to that, because that workflow is no longer recommended and was therefore removed from the documentation. The basic idea was to start with example-drops-8-composer and manually commit and push vendor et. al. to Pantheon after running Composer locally.

It would be helpful, I think, to check the top commit and see if it's an artifact push from Build tools (can inspect commit comment and/or look for the build metadata json file). If it's not there, then we could just say that the site is "some other kind" of empty upstream site (not build tools).

2022-01-31 23:19 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +                $this->getUpstreamExtraAdvice($upstreamId)
It seems undesirable to have the branching logic in getUpstreamExtraAdvice duplicated in the conditionals below. e.g. if getUpstreamExtraAdvice says that the upstream is Build Tools vs the upstream is some other kind of empty upstream site, the upgrade advice will also be different.

2022-01-31 23:21 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +Advice: convert the site to use "drupal-recommended" Pantheon Upstream
This is good advice for sites that are on the "No CI workflow", etc., but if the site is on Build Tools, the site owner will likely want to remain on Build Tools to keep their CI. If they do not need their CI (e.g. if they have no tests, no CSS compilation, etc., then they could switch to drupal-recommended).

2022-01-31 23:23 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +                $this->getUpstreamExtraAdvice($upstreamId)
Or perhaps the advice won't be that much different, but it still seems better to remove the parallel set of `if` statements, and just copy the text from each branch into the output of the different adviseOn... methods.

2022-01-31 23:31 UTC, greg-1-anderson commented on src/Utils/Git.php
> +            // If remote show fails is because it does not exist. Add it.
Code style: `catch` should be for exceptional code paths. This is the standard code path, i.e. when the remote does not exist, we do the primary function of this method. It is better style to check the exit status of the command and have an early-exit if the remote exists.

Doing this would require having another version of `execute` with a different signature that returned the status code. The current execute could call that one and thrown an exception if there was an error.

I care 2 out of 10, though; optional.

2022-01-31 23:32 UTC, greg-1-anderson requested changes
Refactor parallel set of `if` statements; consider suggestion to refactor execute (optional).

2022-02-01 01:00 UTC, kporras07 commented on src/Commands/AdviseCommand.php
> +Advice: convert the site to use "drupal-recommended" Pantheon Upstream
Yep, build tools scenario is covered some lines below.

2022-02-01 01:02 UTC, kporras07 commented on src/Commands/AdviseCommand.php
> +                $this->getUpstreamExtraAdvice($upstreamId)
Fixed. I'll tackle the rest of this tomorrow :)

2022-02-01 01:14 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +Advice: convert the site to use "drupal-recommended" Pantheon Upstream
Ah, I missed that / forgot. It looks like the advice here is correct, except it might get the wrong answer if there is a leftover build-metadata.json in the repo, e.g. because the site started out build tools and then was switched to the no ci workflow. If build tools is in active use, then build-metadata.json will be modified in the commit at the HEAD of the main branch. This can be follow-on work.

2022-02-01 21:08 UTC, kporras07 commented on src/Commands/AdviseCommand.php
> +            return 'This site was created by the process described by the Terminus Build Tools guide (https://pantheon.io/docs/guides/build-tools/).';
Done. But I'm not sure what message to print it it's empty but not build tools. I'm just omitting that atm

2022-02-01 21:11 UTC, kporras07 commented on src/Commands/AdviseCommand.php
> +Advice: convert the site to use "drupal-recommended" Pantheon Upstream
Fixed

2022-02-01 21:27 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +            return 'This site was created by the process described by the Terminus Build Tools guide (https://pantheon.io/docs/guides/build-tools/).';
You should advise that the site *may* stay as it is, but it is recommended to convert it to pantheon-systems/drupal-recommended.

2022-02-01 21:28 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +            $this->writeln('This site was created from the dashboard after November 30, 2021 and is using the recommended upstream.');
It might have been created before the cut-over date and subsequently converted. I'd just say that the site is using the recommended upstream, and therefore no conversion is necessary.

2022-02-01 21:30 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +        $this->writeln('This site was created from the dashboard prior to November 30, 2021.');
Maybe "This site is using the upstream pantheon-systems/drupal-project, which was the default upstream prior to November 30, 2021."

2022-02-01 21:46 UTC, kporras07 commented on src/Utils/Git.php
> +            // If remote show fails is because it does not exist. Add it.
Fixed. Please take a look to the new implementation

2022-02-01 21:46 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +(https://pantheon.io/docs/guides/build-tools/).
This advice could be more specific, and state that the user might want to convert to drupal-recommended if CI isn't needed (not running tests, not compiling css, etc.), but should stay on build tools if they do need CI.

The advice if !$isBuildTools should be really similar: it's recommended to go to drupal-recommended, but the user may stay on the same workflow if they wish.

2022-02-01 22:18 UTC, kporras07 commented on src/Commands/AdviseCommand.php
> +(https://pantheon.io/docs/guides/build-tools/).
I think this is also fixed

2022-02-09 16:18 UTC, greg-1-anderson approved these changes

2022-02-09 20:06 UTC, merged