[CMS-553] Add pending packages from composer require and require-dev sections.
pantheon-systems/terminus-conversion-tools-plugin pull request #16
Opened 2022-02-02 23:43 UTC by kporras07

After copying regular modules, themes and libraries, conversion:composer now compares original and actual composer.json and adds the missing packages both in require and require-dev sections.

I also added a couple of notices when this process finishes.

2022-02-02 23:47 UTC, kporras07 commented on src/Commands/ConvertToComposerSiteCommand.php
> +                    sprintf('Failed adding %s composer package: %s', $arguments[0], $t->getMessage())
This could fail if adding a package in a repository added to the project. The error will be logged but the process will continue. That's why I added some notices after this. Is that enough?

Also, packages requiring config (i.e. composer/installers, oomphinc/composer-installers-extender, cweagans/composer-patches) won't get the config copied over but a notice will be printed for the user to manually do it.

Given that we're pushing to a multidev I think this is a good intermediate point at least for now, thoughts?

2022-02-02 23:47 UTC, kporras07 commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
Packages requiring config (i.e. composer/installers, oomphinc/composer-installers-extender, cweagans/composer-patches) won't get the config copied over but a notice will be printed for the user to manually do it.

Given that we're pushing to a multidev I think this is a good intermediate point at least for now, thoughts?

2022-02-03 00:23 UTC, greg-1-anderson commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
Seems like it would be a good idea to copy over config at least for well-known plugins. Maybe log for any keys in extra NOT copied, after transferring known things?

2022-02-03 00:27 UTC, kporras07 commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
Sounds good.
- oomphinc/composer-installers-extender
- cweagans/composer-patches
- composer/installers

Something else?

2022-02-03 12:19 UTC, jabxjab requested changes

2022-02-03 12:19 UTC, jabxjab commented on src/Commands/ConvertToComposerSiteCommand.php
> +            $arguments[] = '-n';
It is better to distinguish arguments and options, like the in the following approach:

```php
if (is_string($project)) {
    $project = [
        'package' => $project,
        'version' => null,
        'is_dev' => false,
    ];
}

$package = $project['package'];

$arguments = [$project['package'], $project['version']];
$options = $project['is_dev'] ? ['--dev'] : [];
$options[] = '-n';

try {
    $this->getComposer()->require(...$arguments, ...$options);
    $this->getGit()->commit(sprintf('Add %s project to Composer', $package));
    $this->log()->notice(sprintf('%s is added', $package));
} catch (Throwable $t) {
    $this->log()->warning(sprintf('Failed adding %s composer package: %s', $package, $t->getMessage()));
}
```

2022-02-03 12:19 UTC, jabxjab commented on src/Utils/Composer.php
> +    public function toArray(): array
suggestion for the method name - `getComposerJsonData()` (`toArray()` is too generic in context of the class)

2022-02-08 00:13 UTC, kporras07 commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
@greg-1-anderson I haven't tested composer-installers-extenders related code (I'll do that later this week). In the meantime, could you take a look to confirm that's what you had in mind? Also, besides these packages (actually I don't think we really need any config for composer/installers other than what's already included in pantheon-upstreams/drupal-recommended), is there any other well-known package you would like to include?

2022-02-08 16:22 UTC, greg-1-anderson commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
Yeah, the code below looks good. I don't have any additional Composer plugins to suggest. The site being migrated might have added additional project types, though; you could check for that and move any new ones over.

2022-02-09 00:57 UTC, kporras07 commented on src/Commands/ConvertToComposerSiteCommand.php
> +        $this->log()->notice('Please note that other composer.json sections: repositories, config, extra, etc should be manually migrated if needed.');
Added

2022-02-10 19:41 UTC, greg-1-anderson approved these changes
Looks like all review comments have been addressed. 👍

2022-02-11 00:48 UTC, kporras07 commented
As part of the errors I found a composer error adding packages from the source repo that failed but that error was catched and logged as expected by the new code. The current actual errors seem to be platform related. Re-testing

2022-02-11 20:18 UTC, kporras07 commented
I think this would be the final run with tests: https://github.com/pantheon-systems/terminus-conversion-tools-plugin/actions/runs/1831269094

2022-02-14 20:06 UTC, merged