[CMS-627] Throw composer exception if composer commands set fails.
pantheon-systems/terminus-conversion-tools-plugin pull request #27
Opened 2022-03-25 00:01 UTC by kporras07

2022-03-25 00:03 UTC, kporras07 commented
Sample output:

```
  [InvalidArgumentException]
  Could not find a matching version of package frdh/mmenu.js. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...


 [error]  There have been errors adding composer packages, please review previous messages.
```

2022-03-28 06:22 UTC, jabxjab requested changes

2022-03-28 06:22 UTC, jabxjab commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
@kporras07 `$errors` is not needed, ie:
```php
// ...
} catch (Throwable $t) {
    $this->log()->error(
        sprintf(
            'Failed updating composer.json: %s',
            $t->getMessage()
        )
    );
     throw new ComposerException(
        'Failed updating composer.json. Please check the logs for more information.'
    );
}
```

2022-03-28 06:22 UTC, jabxjab commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +            $errors++;
@kporras07  `$errors` is redundant, please see the previous comment

2022-03-28 20:25 UTC, kporras07 commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
As per the ticket, we want to let the current set of composer command to run and then fail with the exception. That's why I was writing it like that. Please let me know if you think your suggestion is still applicable having this bit of context

2022-03-28 20:41 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
The error counting needs to happen inside the `foreach`, though; in its current location, the first exception thrown will still abort the entire loop.

2022-03-29 19:07 UTC, kporras07 commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
@greg-1-anderson I'm not sure I'm following. We catch throwable and increment errors so that after the try-catch block we throw ComposerException that will actually stop the process. Am I missing something?

2022-03-29 23:38 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
Yes; $errors will only ever be zero or 1, because if some of the code inside `foreach ($drupalRecommendedComposerDependencies as $dependency) {` throws, the loop will not continue, because the `try` is outside the loop instead of inside.

2022-03-30 22:04 UTC, kporras07 commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
ohhhh! That makes sense. Thanks!

2022-04-05 22:09 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
I think that the outer try-catch can just go away now. Let it throw all the way out of the command if something outside the inner loop fails.

2022-04-05 22:12 UTC, kporras07 commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +            $errors++;
Done!

2022-04-07 23:58 UTC, greg-1-anderson commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +        if ($errors) {
This should happen before the `composer update`

2022-04-08 01:17 UTC, kporras07 commented on src/Commands/ConvertToDrupalRecommendedSiteCommand.php
> +        if ($errors) {
Done!

2022-04-12 05:45 UTC, jabxjab approved these changes

2022-04-12 21:04 UTC, merged