[CMS-624] Use drupal/core if already in use.
pantheon-systems/terminus-conversion-tools-plugin pull request #28
Opened 2022-03-25 00:19 UTC by kporras07

2022-03-25 16:09 UTC, greg-1-anderson commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +                if ($dependency['package'] === 'drupal/core') {
Could we use the absence of `drupal/core-recommended` in the source project as the trigger for removing it here? Would need to determine this with a separate loop, probably, but it would be preferable. It's possible that a project might declare both drupal/core and drupal/core-recommended, in which case we wouldn't want to remove it here.

2022-03-25 16:11 UTC, greg-1-anderson requested changes
Act based on the lack of drupal/core-recommended, rather than the presence of drupal/core.

2022-03-28 06:24 UTC, jabxjab commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +        $drupalPackage = $this->sourceComposerJson['require']['drupal/core'] ? 'drupal/core' : 'drupal/core-recommended';
@kporras07 Should this be `isset($this->sourceComposerJson['require']['drupal/core']) ? ...`?

2022-03-29 01:39 UTC, kporras07 commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +                if ($dependency['package'] === 'drupal/core') {
Approach updated in getDrupalComposerDependencies. If that function returns that drupal/core will be required that means that core-recommended should be removed, otherwise, it will stay

2022-03-29 04:28 UTC, jabxjab approved these changes

2022-03-29 19:02 UTC, merged