[CMS-626] Make printed commands aware of lando environments.
pantheon-systems/terminus-conversion-tools-plugin pull request #29
Opened 2022-03-25 14:02 UTC by kporras07

2022-03-25 16:06 UTC, greg-1-anderson commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +trait LocalEnvironmentAwareTrait
"___AwareTrait" implies participation in dependency injection from league/container inflection. It would be better to avoid using "AwareTrait" when inflection is not being used. Not sure if there are other examples of this in the code already. Maybe "TerminusCommandDeterminatorTrait" or "LocalEnvironmentInspectorTrait"?

Could also just use a utility class here. Usually, Traits are used (e.g. in DI) because DI necessitates an interface, and every class that implements the interface must provide a body for the requisite methods (which the Trait provides). Since there is no interface here, it might be clearer to just have a utility class. The caching could be dispensed with; if you anticipated potentially expanding the use of this trait to something else that might have greater need for caching, you could leave it a trait.

2022-03-25 16:06 UTC, greg-1-anderson requested changes
Looks fine, just some naming things issues.

2022-03-25 16:09 UTC, kporras07 commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +trait LocalEnvironmentAwareTrait
I'd like to keep it as a trait to make the usage easier and also because if wanted, this could be expanded to other local env solutions.

I'll update the trait name as suggested

2022-03-28 06:28 UTC, jabxjab commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +        if (empty($this->isLando)) {
@kporras07 IMHO, better to use `isset()` this case

2022-03-28 06:29 UTC, jabxjab commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +        if (empty($this->terminusCommand)) {
@kporras07 IMHO, better to use `isset()` this case

2022-03-28 06:41 UTC, jabxjab commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +trait LocalEnvironmentAwareTrait
My suggestion on this would be to put a primary `getTerminusExecutable()` method directly into `ConversionCommandsTrait` like this:
```php

    /**
     * Returns the terminus executable.
     *
     * @return string
     */
    protected function getTerminusCommand(): string
    {
        if (isset($this->terminusCommand)) {
            return $this->terminusExecutable;
        }

        if (getenv('LANDO_APP_NAME')) {
            // Lando-based environment.
            return $this->terminusExecutable = 'lando terminus';
        }

        return $this->terminusExecutable = 'terminus';
    }
```
Also I suggest to change `"command"` to `"executable"` in method/property name.

2022-03-28 06:43 UTC, jabxjab requested changes
Move `getTerminusExecutable()` into `ConversionCommandsTrait`

2022-03-29 01:20 UTC, kporras07 commented on src/Commands/Traits/LocalEnvironmentAwareTrait.php
> +trait LocalEnvironmentAwareTrait
Done, thanks

2022-03-29 04:26 UTC, jabxjab approved these changes

2022-03-29 19:03 UTC, merged