Cms 623 in progress advise
pantheon-systems/terminus-conversion-tools-plugin pull request #34
Opened 2022-04-01 14:44 UTC by kporras07

Draft until #32 gets merged

2022-04-01 20:19 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +You may run the conversion:advise command again to check your progress and see the next steps again.
This is the last step; once the upstream is set, then they're done. Perhaps this message should say that they can run the advise command again to confirm that the conversion was completed successfully.

2022-04-01 20:21 UTC, greg-1-anderson commented on src/Commands/AdviseCommand.php
> +Drupal Recommended (drupal-recommended)
Add a little whitespace & indentation around this text, here and elsewhere, as shown in the example in the story (CMS-631)

2022-04-01 20:23 UTC, greg-1-anderson commented
Looks good, just have a couple minor requests above. Also, could you show an example of the output from running the advise command in each of the scenarios, either here or on the JIRA card?

2022-04-01 20:23 UTC, greg-1-anderson requested changes
See above

2022-04-04 21:23 UTC, kporras07 commented
@greg-1-anderson done.

Added output examples to CMS-623

2022-04-05 09:24 UTC, jabxjab commented on src/Commands/Traits/ConversionCommandsTrait.php
> +        return in_array('conversion', $environments);
tip: strict comparison is preferable for `in_array` (i.e. `in_array('conversion', $environments, true);`)

2022-04-05 09:25 UTC, jabxjab commented on src/Commands/Traits/ConversionCommandsTrait.php
> +    protected function conversionMultidevExist(): bool
tip: `isConversionMultidevExist`

2022-04-05 22:28 UTC, greg-1-anderson approved these changes
LGTM!

2022-04-05 22:29 UTC, merged