[CMS-628] New conversion:upgrade-d9 command.
pantheon-systems/terminus-conversion-tools-plugin pull request #36
Opened 2022-04-12 00:08 UTC by kporras07

2022-04-12 00:09 UTC, kporras07 commented on src/Commands/UpgradeD9Command.php
> +                'package' => 'phpunit/phpunit',
I added this here because I was testing this locally with a site that was converted to composer from example-drops8-composer and had phpunit (5 or 6) and it was impossible to upgrade to D9. If we have a list of other common packages, we could easily add them here

2022-04-12 07:46 UTC, jabxjab requested changes

2022-04-12 07:46 UTC, jabxjab commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +        $drupalConstraint = $forceDrupalVersion;
Var assignment and `if` could be avoided with this:
```php
$drupalConstraint = $forceDrupalVersion
  ?? $this->sourceComposerJson['require']['drupal/core-recommended']
  ?? $this->sourceComposerJson['require']['drupal/core']
  ?? '^8.9';
```

2022-04-12 07:46 UTC, jabxjab commented on src/Commands/UpgradeD9Command.php
> +            $pantheonYmlContent = array_merge($pantheonYmlContent, Yaml::parseFile(Files::buildPath($this->getLocalSitePath(), 'pantheon.upstream.yml')));
Line exceeds 120 chars

2022-04-12 07:46 UTC, jabxjab commented on src/Commands/UpgradeD9Command.php
> +     * @throws \Psr\Container\ContainerExceptionInterface
Missing `@throws \Pantheon\TerminusConversionTools\Exceptions\Composer\ComposerException`

2022-04-12 07:46 UTC, jabxjab commented on src/Commands/UpgradeD9Command.php
> +     * Require updated packages from a fixed list if they are installed in current site.
Missing 
```
* @throws \Pantheon\TerminusConversionTools\Exceptions\Composer\ComposerException
* @throws \Pantheon\TerminusConversionTools\Exceptions\Git\GitException
```

2022-04-12 07:46 UTC, jabxjab commented on src/Commands/UpgradeD9Command.php
> +     *   SSH connection string.
Missing `@throws \Pantheon\Terminus\Exceptions\TerminusException`

2022-04-12 07:46 UTC, jabxjab commented on tests/functional/ConversionCommandsUpgradeD9Test.php
> + * Uses a site fixture based on https://github.com/pantheon-fixtures/site-drupal8-non-composer custom upstream.
Just to double-check, please confirm this is the actual fixture repo for the test

2022-04-13 07:14 UTC, jabxjab commented on src/Commands/UpgradeD9Command.php
> +                'package' => 'phpunit/phpunit',
I doubt we should hardcode this. Seems like a user-specific issue (i.e. a user should manually resolve such incompatibilities). @greg-1-anderson, could you please advise on this?

2022-04-20 06:28 UTC, jabxjab approved these changes

2022-04-20 20:32 UTC, merged