Migrate composer repositories.
pantheon-systems/terminus-conversion-tools-plugin pull request #39
Opened 2022-04-13 03:04 UTC by kporras07

2022-04-13 08:07 UTC, jabxjab requested changes

2022-04-13 08:07 UTC, jabxjab commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +        $currentRepositories = &$currentComposerJson['repositories'] ?? [];
Error - "Only variables can be passed by reference". 
Consider refactoring into a more compact variant like the following:
```php
$sourceRepositories = $this->sourceComposerJson['repositories'] ?? [];
if (!$sourceRepositories) {
    return;
}

$composerJson = $this->getComposer()->getComposerJsonData();
$repositories = $composerJson['repositories'] ?? [];

$diff = array_filter(
    $sourceRepositories,
    fn($sourceRepository) => !array_filter(
        $repositories,
        fn($repository) => $repository == $sourceRepository
    )
);
if (!$diff) {
    return;
}

$composerJson['repositories'] = array_merge($repositories, $diff);
$this->getComposer()->writeComposerJsonData($composerJson);
```

2022-04-14 04:37 UTC, kporras07 commented on src/Commands/Traits/MigrateComposerJsonTrait.php
> +        $currentRepositories = &$currentComposerJson['repositories'] ?? [];
Thanks! Fixed

2022-04-14 05:52 UTC, jabxjab approved these changes

2022-04-18 20:18 UTC, merged